### ISSUE TITLE
Replace wrapper by proxy

### ISSUE THREAD

**Issue by pldupont** [pldupont/SQLIDetectionDriver#5]

**Comment by sberthiaume** [comment]
Just a thought, but if we replace the wrappers by dynamic proxies, wouldn't we have a greater risk of having loopholes when we migrate from one JDK to another? For example, if in JDK9 they add a new createStatement(...) to the connection object and we miss it, it would call the implementation straight and we would create a loophole.

I don't like how much "pass-through" code we need to have, but it might be the best way to have some sort of "built-in" integrity check,

**Comment by pldupont** [comment]
I know, I realize the same thing while trying to implement it. But on the other side, we might be able to support multiple version.
